### ISSUE TITLE
Recent Python component upgrades break ansible k8s_info functionality

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/OpenShift4-RollOut#481]
**Describe the issue**
Recent OS patching revealed issues with ansible playbooks not able to run correctly and instead generate the following message.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Host value http://localhost should start with https:// when talking to HTTPS endpoint
fatal: [localhost]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1609394741.33-22201-173486061827444/AnsiballZ_k8s_info.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1609394741.33-22201-173486061827444/AnsiballZ_k8s_info.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1609394741.33-22201-173486061827444/AnsiballZ_k8s_info.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.clustering.k8s.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_k8s_info_payload_C3cNgi/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py", line 179, in <module>
      File "/tmp/ansible_k8s_info_payload_C3cNgi/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py", line 175, in main
      File "/tmp/ansible_k8s_info_payload_C3cNgi/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py", line 148, in execute_module
      File "/tmp/ansible_k8s_info_payload_C3cNgi/ansible_k8s_info_payload.zip/ansible/module_utils/k8s/common.py", line 200, in get_api_client
      File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 71, in __init__
        self.__discoverer = discoverer(self, cache_file)
      File "/usr/lib/python2.7/site-packages/openshift/dynamic/discovery.py", line 259, in __init__
        Discoverer.__init__(self, client, cache_file)
      File "/usr/lib/python2.7/site-packages/openshift/dynamic/discovery.py", line 31, in __init__
        self.__init_cache()
      File "/usr/lib/python2.7/site-packages/openshift/dynamic/discovery.py", line 78, in __init_cache
        self._load_server_info()
      File "/usr/lib/python2.7/site-packages/openshift/dynamic/discovery.py", line 165, in _load_server_info
        self.client.configuration.host)
    ValueError: Host value http://localhost should start with https:// when talking to HTTPS endpoint
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```
A sizable portion of the current ansible playbooks needed to complete configuration of a new cluster rely upon the k8s_info module working correctly, thus this issue needs to be addressed with a permanent solution if possible, and a work-around if viable to get the playbooks working again.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] confirm cause.
- [x] apply work-around if available
- [ ] confirm if permanent solution is available and test in LAB
- [ ] apply permanent solution in PROD

**Comment by wmhutchison** [comment]
Work-around achieved on all OCP4 UTIL servers for now. Moving to Backlog until more time can be allocated into research into a longer-term fix.

**Comment by StevenBarre** [comment]
The python2-kubernetes package has been rolled back to v11 in the RPM repos. So a `yum update python2-kubernetes` will fix this now.
